version: '3'

#Adding services web and redis
#Setting the volume with source as app folder and target as /code in container
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"

